# Configuration
env:
    global:
        secure: "A/4lXSJK/UcM+kyz1krUF88Ar9OJJlWEQBC63H+eSbnAwIzm6pt3IWOuTzZoEihCbBFdrd2cx+/7aBNbTM0Bc7oje01KpG/d2vSZGKQj279+WqrIWyr4YHgoVd8ZlwTe7hNkG0mlpAwjHJ2qoO6GhiFyyZoB07253wsXOoAkU0cyXkYVlKHpxv0lcN9r38ysWuEx6PbTA5vPB4/J3SpTJVoEMhmSpRMawhc46GqCI+e0KKBclRth5rpH3LPmGXgacumWP+VDyjSHcf6agI3jbYzaEgzgprPGxZJCLXsXMS3EwEAfD79GUStdD5rdtfp+A3ZKM8SLt4OBiWWl8ug+IqY76LYb8AZmG3yHPF1ywOPyuH2WWBDxRa28fmqUVo2fssY1eMoxxMOO1Gu2KyvgP2cHC8mU8prVlsGJwyxLGC1eeKnUL8i1stKnypTwox1FqKBgZsPtcxgHneuNV0ZCxz5rSw43WYFN4UsgSEBPdBCOYI1/6Kl9hv5LGwFVlgiMCHtQDp7Hu4FhAhsRLjymgOEsfVGxoDqQXaZzt5bJdWuZDbMFaPCLnrJoj2ODSXFhqKz28hKT78ej+9/6Pxoeg+XZt+rJ4i4rdvrrI+MYrhwt3utYpOH0It8Ri/9bFafMOCXOXoipAr6I8y58u7cAGEQowIuLkiC5wzCNDXg3L6o="
sudo: false
language: node_js

node_js:
    - "stable"

# The pre-install script
before_install:
    - yarn global add greenkeeper-lockfile@1

# The install script
install:
    - yarn install

# The pre-build script
before_script:
    - greenkeeper-lockfile-update
    - yarn run lint

# The build script
script:
    - yarn run build

# The post-build script
after_script:
    - greenkeeper-lockfile-upload

# Disable email notifications
notifications:
    email: false

# WHO IN THE F# (the programming language) DOESN’T SUPPORT TABS IN 2017? '	' <- tab
# P.S.: F# (the programming language) also doesn’t support tabs, and that's terrible
